spring.application.name=PcBuildingWeb
spring.datasource.url=jdbc:mysql://localhost:3306/dbms?useSSL=false&serverTimezone=\
  UTC&useLegacyDatatimeCode=false
spring.datasource.username=root
spring.datasource.password=

#Hibernate Property Here
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#Hibernate auto ddl
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=DEBUG 

